### ISSUE TITLE
Helensburgh, NSW

### ISSUE THREAD

**Issue by gittastic** [LukePrior/nbn-upgrade-map#1]
Hey, the map is great. This is just a request for Helensburgh NSW to be added please :)

**Comment by LukePrior** [comment]
Generating it now: https://github.com/LukePrior/nbn-upgrade-map/actions/runs/5037735588

**Comment by LukePrior** [comment]
Here you go: https://lukeprior.github.io/nbn-upgrade-map/?suburb=helensburgh

![image](https://github.com/LukePrior/nbn-upgrade-map/assets/22492406/4812ce58-c284-448c-a496-a5121bcd4409)

**Comment by gittastic** [comment]
@LukePrior please could I get Helenburgh, NSW updated. Some streets have changed status recently. Thank you!
