### ISSUE TITLE
Bella Vista NSW 2153 North Rocks NSW 2151 ??

### ISSUE THREAD

**Issue by peter-mc** [LukePrior/nbn-upgrade-map#10]
Any chance you could also add Bella Vista NSW 2153 and North Rocks NSW 2151 ??

**Comment by LukePrior** [comment]
Bella Vista: https://lukeprior.github.io/nbn-upgrade-map/?suburb=bella-vista&state=NSW

**Comment by LukePrior** [comment]
Done.
