### ISSUE TITLE
Not all upgrade types shown on map

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#103]
As discovered in https://github.com/LukePrior/nbn-upgrade-map/issues/97 some properties have upgrades that are not handled by the existing JS code in index.html:

fillColor: feature.properties.upgrade == "FTTP_SA" ? "#00ff00" : feature.properties.tech == "FTTP" ? "#00aa00" : feature.properties.tech == "HFC" ? "#ffa500" : feature.properties.upgrade == "UNKNOWN" ? "#888888" : "#ff0000",

**Comment by lyricnz** [comment]
Across all current properties, the "upgrade" value tallies are:
```
Upgrade types:
NULL_NA 807283
FTTP_SA 178878
UNKNOWN 82534
FTTC_CT 47
FTTN_CT 1854
FTTP_NA 18321
FTTB_CT 12
FW_CT 169
HFC_CT 8
FTTC_NA 1
SAT_CT 1
FTTN_NA 1
```

**Comment by lyricnz** [comment]
FTTP/FTTC/FTTB/FTTN/FW/HFC/SAT are technology types
CT = ? current technology?
NA = ? not available?
SA = ? solution available?

**Comment by peter-mc** [comment]
I don't know for sure, but some of them seem to be abbreviations of other fields in the NBN record

CT = "statusMessage": "connected-true",
C = "statusMessage": "connected",

SA = Service Available ??

**Comment by lyricnz** [comment]
We still need to update the JS to show more types.  The current tallies are, fwiw:

Upgrade types:
  FTTB_CT: 363
  FTTC_CT: 1272
  FTTC_NA: 5
  FTTN_CT: 13821
  FTTN_NA: 3
  FTTP_NA: 93429
  FTTP_SA: 1374195
  FW_CT: 1260
  FW_NA: 2
  HFC_CT: 81
  NULL_NA: 6386338
  SAT_CT: 16
  UNKNOWN: 784695

**Comment by LukePrior** [comment]
Hmm ok what fields should we have corresponding to what legends?

**Comment by peter-mc** [comment]
Given the map is about FTTP upgrades, I'd think FTTP_NA (FTTP upgrade imminent) and FTTP_SA (FTTP upgrade available) are the most important ones

**Comment by LukePrior** [comment]
Alright the map has been updated with a new legend, open to feedback

**Comment by peter-mc** [comment]
wow, what a difference, so many areas are ready for upgrades already...

thanks Luke!

**Comment by lyricnz** [comment]
I've created a PR https://github.com/LukePrior/nbn-upgrade-map/pull/212 to split FTTP_SA and FTTP_NA into different shades of green.  Example

<img width="690" alt="image" src="https://github.com/LukePrior/nbn-upgrade-map/assets/122371/c6cb9b6a-4bf9-4783-a5c5-ee65f798031a">

But I see that elsewhere someone has complained about the green being hard to read - so these changes may need updates (then) too.

**Comment by LukePrior** [comment]
I think that covers this for now
