### ISSUE TITLE
Uncaught errors in GHA

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#105]
https://github.com/LukePrior/nbn-upgrade-map/actions/runs/5151662940/jobs/9277039475

```
2023-06-02 04:09:43,424 ERROR Unhandled exception: 'suggestions'
2023-06-02 04:09:43,424 ERROR Unhandled exception: 'suggestions'
2023-06-02 04:09:43,424 ERROR Unhandled exception: 'suggestions'
2023-06-02 04:09:43,424 ERROR Unhandled exception: 'suggestions'
2023-06-02 04:09:43,424 ERROR Unhandled exception: 'suggestions'
```

**Comment by lyricnz** [comment]
Probably the NBN data didn't come back with the "suggestions" field
```python
loc_id = self.get_nbn_data_json(self.LOOKUP_URL + urllib.parse.quote(address))["suggestions"][0]["id"]
```

**Comment by LukePrior** [comment]
I'm also seeing this one a bit

`ERROR Unhandled exception: list index out of range`

**Comment by lyricnz** [comment]
Will add some more key/range checks

**Comment by LukePrior** [comment]
not sure what this one is: 

`2023-06-04 12:15:30,197 WARNING Error fetching NBN data for 17 DROVER PLACE NARRANDERA 2700: Expecting value: line 1 column 1 (char 0)`

**Comment by lyricnz** [comment]
I think it means empty http response?

**Comment by lyricnz** [comment]
The `Unhandled exception: 'suggestions'` fixed by https://github.com/LukePrior/nbn-upgrade-map/blob/main/code/nbn.py#L38

```python
suggestions = result.get("suggestions", [])
```

And I haven't seen the others recently.  Can't do too much about the empty HTTP response.  Can this be closed?
