### ISSUE TITLE
Create process for building and publishing cut-down DB image

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#106]
Per https://github.com/LukePrior/nbn-upgrade-map/pull/101 it would be useful if there was a GHA that could run the script, and publish the resulting image.

Maybe the script could be updated to copy/reuse the version tag from the upstream repo. https://github.com/minus34/gnaf-loader/releases

**Comment by lyricnz** [comment]
Ran out of space attempting to extract the data from the DB in a GHA
https://github.com/lyricnz/nbn-upgrade-map/actions/runs/5151993321/jobs/9277689611

```
docker: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /var/lib/postgresql/15/main/base/5/17654: no space left on device.
```

**Comment by lyricnz** [comment]
I've manually pushed my image to lyricnz/nbn-upgrade-map-db:latest in the meantime

**Comment by LukePrior** [comment]
Oh yes in terms of running out of space you might need to mess around with `easimon/maximize-build-space` to get enough storage.

**Comment by lyricnz** [comment]
Maybe could use a multi-stage Dockerfile and run commands in the minus34/gnafloader one to extract the data.  I did a quick try, but looks like no disk-space free in the container to write the export...

**Comment by lyricnz** [comment]
In and working
