### ISSUE TITLE
Please add Tahmoor (2573) and Camden (2570) (NSW)

### ISSUE THREAD

**Issue by PULterHO** [LukePrior/nbn-upgrade-map#11]

**Comment by LukePrior** [comment]
Tahmoor: https://lukeprior.github.io/nbn-upgrade-map/?suburb=tahmoor&state=NSW

**Comment by LukePrior** [comment]
Camden: https://lukeprior.github.io/nbn-upgrade-map/?suburb=camden&state=NSW
