### ISSUE TITLE
Cranbourne North VIC - Large number of unmatched properties

### ISSUE THREAD

**Issue by LukePrior** [LukePrior/nbn-upgrade-map#118]
![image](https://github.com/LukePrior/nbn-upgrade-map/assets/22492406/13ac6190-f0fb-4d07-bfde-1680d96ff618)

**Comment by LukePrior** [comment]
`2023-06-05 02:55:23,844 INFO Location ID types: {'Other': 1092, 'LOC': 7474, 'None': 3}`

https://lukeprior.github.io/nbn-upgrade-map/?suburb=cranbourne-north&state=VIC

**Comment by LukePrior** [comment]
Will need to investigate further but realised might just not be serviced by the NBN network and is with a different provider.

**Comment by lyricnz** [comment]
Yup

> OptiComm delivers a fibre network to this area
> For specific information on how to connect your premises contact the existing provider.
> Website: http://www.opticomm.net.au

<img width="1704" alt="Screenshot 2023-06-05 at 1 19 13 pm" src="https://github.com/LukePrior/nbn-upgrade-map/assets/122371/a880db55-8b11-469f-871f-dbbbbe17f76f">

**Comment by LukePrior** [comment]
Aha
