### ISSUE TITLE
Sparse Checkout for local usage?

### ISSUE THREAD

**Issue by LukePrior** [LukePrior/nbn-upgrade-map#123]
Might be a good idea to suggest a sparse checkout excluding all the results if people have limited storage or network.

https://stackoverflow.com/questions/33933702/git-checkout-except-one-folder

**Comment by LukePrior** [comment]
This is now in use here: https://github.com/LukePrior/nbn-upgrade-map/commit/91d9fe1c294a5b5ea761c5393cb4d1214d7926c0

**Comment by LukePrior** [comment]
TODO: have an option in `results.py` to only just update `results.json` so that sparse checkout can be used in the main action

**Comment by sua16okay** [comment]
Hi, I am very bad with all of this. I've run it in docker, but how/where do I enter the User and password? I can't find local access....I get this in logs

2023-07-24 20:30:29 2023-07-24 10:30:29.532 UTC [59] [unknown]@[unknown] LOG:  invalid length of startup packet

**Comment by LukePrior** [comment]
> Hi, I am very bad with all of this. I've run it in docker, but how/where do I enter the User and password? I can't find local access....I get this in logs
> 
> 2023-07-24 20:30:29 2023-07-24 10:30:29.532 UTC [59] [unknown]@[unknown] LOG: invalid length of startup packet

Please open a new issue if you are still having problems
