### ISSUE TITLE
Decide and document on Python version requirements

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#125]
In chat, you rejected a change I suggested because you wanted to maintain compatibility with older versions of python (even older than the 3.8 used by CI).

Please document this requirement somewhere, as it impacts the type of code that can be used (eg: walrus operator, type-hinting, asyncio, structural pattern matching, etc)

**Comment by lyricnz** [comment]
I think many modern Python projects prescribe 3.10

**Comment by lyricnz** [comment]
Any updates @LukePrior ?

**Comment by LukePrior** [comment]
Thinking about it yeah makes sense to target a modern version. I guess since the project is standalone and mostly run using GitHub Actions we can target a modern version such as 3.10 or 3.11 for the newer features and longer security support.

**Comment by lyricnz** [comment]
I think 3.11 is "too new" to require - it's not available easily on some fairly modern platforms.

**Comment by LukePrior** [comment]
Honestly in that case I'm pretty happy to pin it anywhere from 3.8 to 3.10

**Comment by lyricnz** [comment]
3.10 please https://docs.python.org/3/whatsnew/3.10.html

**Comment by LukePrior** [comment]
Perfect 3.10 it is.
