### ISSUE TITLE
CANBERRA

### ISSUE THREAD

**Issue by LukePrior** [LukePrior/nbn-upgrade-map#13]

**Comment by treaddy** [comment]
Hey mate love the idea. Great job executing it. Can you please add Conder, Gordon, Calwell and Casey in ACT. I noticed Banks is already in the results list :) cheers.

**Comment by treaddy** [comment]
Hey @LukePrior just curious, noticed the ACT Suburbs have shown up in the all_suburbs.json. Does this mean they should now show up in lukeprior.github.io? Or do they still need to be added to the results/ACT folder / results.json? Cheers!

**Comment by LukePrior** [comment]
The suburbs are being added in the order they appear in this file: https://github.com/LukePrior/nbn-upgrade-map/blob/main/results/suburbs.json#L1542

This is the current progress

Progress vs Listed Suburbs:
  ACT: 1 / 18  (5.6%)
  NSW: 279 / 473  (59.0%)
  NT: 0 / 13  (0.0%)
  QLD: 3 / 386  (0.8%)
  SA: 0 / 151  (0.0%)
  TAS: 0 / 31  (0.0%)
  VIC: 2 / 247  (0.8%)
  WA: 0 / 224  (0.0%)
  TOTAL: 285 / 1543  (18.5%)

**Comment by LukePrior** [comment]
done
