### ISSUE TITLE
Map Offline?

### ISSUE THREAD

**Issue by AndyMandy112** [LukePrior/nbn-upgrade-map#134]
Is the map down? It's been timing out for me for the last few hours.

**Comment by LukePrior** [comment]
I just tested and seems to be fine, I wonder if it's a GitHub rate limit thingy.

**Comment by lyricnz** [comment]
Which url are you looking at?  https://lukeprior.github.io/nbn-upgrade-map ?

**Comment by LukePrior** [comment]
I'm going to close this, but if more issues arrive just leave a comment.
