### ISSUE TITLE
Create process for updating list of announced suburubs

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#139]
Where did the current data come from?

The newest I could find was from the popup on https://www.nbnco.com.au/corporate-information/media-centre/media-statements/nbnco-announces-suburbs-and-towns-where-an-additional-ninty-thousand-homes-and-businesses-will-become-eligible-for-fibre-upgrades

**Comment by lyricnz** [comment]
I note that the list at https://www.finder.com.au/nbn-upgrades-suburbs-faster-internet-feb-2023#table is missing a few
eg O’CONNOR ACT
eg TOWNSVILLE QLD

**Comment by lyricnz** [comment]
"TOWNSVILLE" in NBN list may be "TOWNSVILLE CITY" + "SOUTH TOWNSVILLE" in our list

**Comment by lyricnz** [comment]
The PR adds O'CONNOR ACT (with straight apostrophe)

**Comment by kiwisg124** [comment]
Load any changes to the suburb dates published here https://www.nbnco.com.au/residential/upgrades/more-fibre#fttn-suburb-list . List was revised 27 July

**Comment by lyricnz** [comment]
See https://github.com/LukePrior/nbn-upgrade-map/issues/215

**Comment by lyricnz** [comment]
The 27 July changes have been integrated. Closing this issue in favour of #215
