### ISSUE TITLE
Support other-territories

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#149]
Support "other territories" (OT)
{'WEST ISLAND', 'HOME ISLAND', 'NORFOLK ISLAND', 'CHRISTMAS ISLAND'}

**Comment by lyricnz** [comment]
I think Australia calls these "External Territories"
https://en.wikipedia.org/wiki/States_and_territories_of_Australia#External_territories

"West Island" and "Home Island" are part of the South Keeling Islands.
https://en.wikipedia.org/wiki/West_Island,_Cocos_(Keeling)_Islands
https://en.wikipedia.org/wiki/Home_Island
https://en.wikipedia.org/wiki/Home_Island#/media/File:Cocos(keeling)_76.jpg

**Comment by lyricnz** [comment]
Interestingly, although the NBN API looks up these addresses (all satellite) they return WA for the state

<img width="693" alt="image" src="https://github.com/LukePrior/nbn-upgrade-map/assets/122371/d49e86be-b4e4-405f-ae8e-284d7cc24076">

**Comment by LukePrior** [comment]
Seems to work: https://lukeprior.github.io/nbn-upgrade-map/?suburb=norfolk-island&state=OT
