### ISSUE TITLE
Add time to results.json data structure

### ISSUE THREAD

**Issue by kiwisg124** [LukePrior/nbn-upgrade-map#150]
Consider adding time field HH24:MI:SS to the results data structure so that it is easier to show productivity ( processing rates ) during after-the-fact performance analysis.

**Comment by lyricnz** [comment]
Isn't that already in there?  The generated-date is in the geojson file


eg https://github.com/LukePrior/nbn-upgrade-map/blob/main/results/ACT/ainslie.geojson?short_path=b7acc62
```
"generated": "2023-06-05T19:37:43.447130",
```

**Comment by lyricnz** [comment]
See #135

**Comment by LukePrior** [comment]
Done see https://github.com/LukePrior/nbn-upgrade-map/blob/main/results/combined-suburbs.json
