### ISSUE TITLE
Include geographic bounds in results

### ISSUE THREAD

**Issue by LukePrior** [LukePrior/nbn-upgrade-map#154]
It would be useful to include the geographic bounds of a suburb in the results folder so that in future the front-end could be modified to automatically load the data as the user pans around the map.

**Comment by lyricnz** [comment]
I think there's (optional?) boundary information in the upstream database.  The process to create our cut-down version could copy/filter that into the smaller DB.

**Comment by LukePrior** [comment]
Oh yeah that would probably be a better approach, as I was initially just thinking of checked the coordinates of each address in the GEOJSON and calculating it that way.

**Comment by lyricnz** [comment]
I had a quick look around the dataset, and... it's a bit complicated.  It should be easy to generate the extents for each suburb directly from the DB

**Comment by lyricnz** [comment]
Wow.  I made a function get_extents_by_suburb() and hit tab, and my IDE automatically created:

```python
    def get_extents_by_suburb(self) -> dict:
        """return the bounding box for each suburb"""
        query = """
            SELECT locality_name, state, ST_Extent(geom)
            FROM address_principals
            GROUP BY locality_name, state
            ORDER BY state, locality_name
        """
        self.cur.execute(query)

        results = {}
        for record in self.cur.fetchall():
            if record.state not in results:
                results[record.state] = {}
            results[record.state][record.locality_name] = record.st_extent

        return results
```

Which would perfectly on the full DB.  It needs a little tweak for our subset, but amazing!

**Comment by lyricnz** [comment]
Using
```
            SELECT locality_name, state, 
                min(latitude) as min_lat,
                max(latitude) as max_lat,
                min(longitude) as min_long,
                max(longitude) as max_long
            FROM address_principals
            GROUP BY locality_name, state
            ORDER BY state, locality_name
```

Works in about 10-20 seconds on my local

**Comment by LukePrior** [comment]
Just saw the file size probably makes sense to compress this one.

**Comment by lyricnz** [comment]
Indent=1 https://github.com/LukePrior/nbn-upgrade-map/pull/158

**Comment by lyricnz** [comment]
It's included as a separate file with PRs above. Will merge this into a bigger structure eventually.  This can be closed @LukePrior
