### ISSUE TITLE
Create process to accelerate detection of service changes

### ISSUE THREAD

**Issue by kiwisg124** [LukePrior/nbn-upgrade-map#155]
This proposed process attempts to harness internet volunteers to pre-process suburb(s) at intervals and so reduce efforts to find the service changes and present more timely results to internet access seekers.

The goal being to reduce the number of API calls performed by the NBN upgrade map application by distributing the workload.

Every address within a state and suburb is examined at periodic intervals.

Motivated service users will be checking their own area for signs of progress.

Should they be proficient, they might submit their findings of locations with a change to the NBN upgrade application team. 

For privacy reasons, the fact of a volunteer being assigned  might be recorded as a binary flag 01 against the suburb.

And the information upload limited to address ID entries commonly LOC###### 

Example: A city in NSW will be orderable Dec-23 and last processed 30-May. At that time 67 FTTP among 6734 service entries in geojson file.

Today results of v2details API finds 82 / 6824 with FTTP technology type (still running).

For suburbs with a small FTTx cohort processing a changed service list will avoid many calls.

For suburbs with HFC there will be many potentially wasted calls if all are checked every time.

**Comment by jebbusjebbus** [comment]
more than happy to lend a hand as long as someone explains the process of how to do it to me.

**Comment by kiwisg124** [comment]
Clarification (idea): 
(1) support services processing on demand during the next available batch window by adding a suburb trigger file to an agreed GIT folder 
(2) enhance main.py 
support an optional premises filename criteria command line argument
when the file name criteria is provided, read the files(s) to determine in-scope services instead of every address provided by database in STATE/SUBURB query results
retrieve each service mentioned in the file 
Call V2 details for the specified LOC ID
parse formatted address2 in HTML response
if the last word is Australia ..
	take second to last word as STATE
	take fourth to last word as SUBURB
	examine technology type, reasonCode, altReasonCode to detect FTTH and services with upgrade potential

Looking at DB design now.

**Comment by lyricnz** [comment]
The DB is just a subset of the upstream GNAF database. It's nothing to do with NBN as such (other than they use/used a copy of the same database).

**Comment by lyricnz** [comment]
With latest code, all announced-suburbs will be reprocessed every 30 days.  Unannounced suburbs will be processed as quickly as possible, looks like about the same.  I'm not sure additional process is required?

**Comment by LukePrior** [comment]
I'm going to adjust the dates around a bit to find a good balance between announced and all update frequency but yeah I think it should be fine.
