### ISSUE TITLE
Website needs a favicon

### ISSUE THREAD

**Issue by LukePrior** [LukePrior/nbn-upgrade-map#162]
Title

**Comment by lyricnz** [comment]
Maybe something from https://www.istockphoto.com/illustrations/fiber-optic-icon

**Comment by lyricnz** [comment]
How about this, @LukePrior ?  Free no-attribution https://www.vecteezy.com/vector-art/2565547-optical-fiber-linear-vector-icon

https://static.vecteezy.com/system/resources/previews/002/565/547/large_2x/optical-fiber-linear-icon-vector.jpg

**Comment by LukePrior** [comment]
I had to update the HTML for it to go, web manifest needs changes in future but this will suffice for now

**Comment by LukePrior** [comment]
Can now be installed on the web and mobile
![image](https://github.com/LukePrior/nbn-upgrade-map/assets/22492406/95c4edc3-038f-43c6-bad7-68bc4b75405e)
![image](https://github.com/LukePrior/nbn-upgrade-map/assets/22492406/62cbd93f-1ddb-4835-be40-ad1fe9c064e2)
