### ISSUE TITLE
Woodvale, WA 6026

### ISSUE THREAD

**Issue by tijjjy** [LukePrior/nbn-upgrade-map#165]
Hi, could you please add Woodvale, Western Australia

**Comment by lyricnz** [comment]
That suburb has been announced for upgrades (April 2025) so will be processed during the current cycle.  We are currently ~71% of the way through that  - see the progress badges on main page.

**Comment by LukePrior** [comment]
done

**Comment by lyricnz** [comment]
Done see https://lukeprior.github.io/nbn-upgrade-map/?suburb=woodvale&state=WA
