### ISSUE TITLE
Please add Anstead, QLD 4070.

### ISSUE THREAD

**Issue by bigjools** [LukePrior/nbn-upgrade-map#166]
Thanks.

**Comment by lyricnz** [comment]
That suburb has not been announced for FTTP upgrades, so it will be processed after all the announced suburbs are done (see the progress badges on the main page https://github.com/LukePrior/nbn-upgrade-map )

**Comment by bigjools** [comment]
Oh interesting, thanks. It's weird because there are already some addresses that are eligible when I checked!

**Comment by lyricnz** [comment]
Do you know somewhere that lists that suburb for upgrade?

I manually processed that suburb, and created a PR.

It looks like there are a few (90) upgrades available

```
❯ grep upgrade results/QLD/anstead.geojson | sort | uniq -c
   1     "upgrade": "FTTN_CT",
  90     "upgrade": "FTTP_SA",
 449     "upgrade": "NULL_NA",
  92     "upgrade": "UNKNOWN",
``

**Comment by bigjools** [comment]
> Do you know somewhere that lists that suburb for upgrade?

I don't, I just knew that there were some places that were eligible. They
happen to be close to the local exchange which is *right* on the edge of
the next suburb, so that probably explains it.

**Comment by lyricnz** [comment]
Done - see https://lukeprior.github.io/nbn-upgrade-map/?suburb=anstead&state=QLD

**Comment by bigjools** [comment]
Excellent, thanks. How weird the suburb is not in the list yet a handful of houses are ready for upgrade.
