### ISSUE TITLE
Kambalda West, WA 6442.

### ISSUE THREAD

**Issue by WCEagles** [LukePrior/nbn-upgrade-map#172]
Hi, Could you please add Kambalda West, WA. It hasn't been announced, but there are areas of FTTC available to upgrade. Cheers.

**Comment by lyricnz** [comment]
PR raised. Breakdown of upgrade type, by count.

```
❯ grep upgrade results/WA/kambalda-west.geojson | sort | uniq -c
   2     "upgrade": "FTTC_CT",
 517     "upgrade": "FTTP_SA",
 449     "upgrade": "NULL_NA",
 113     "upgrade": "UNKNOWN",
```

**Comment by lyricnz** [comment]
Done https://lukeprior.github.io/nbn-upgrade-map/?suburb=kambalda-west&state=WA
