### ISSUE TITLE
Improve arguments to main.py

### ISSUE THREAD

**Issue by LukePrior** [LukePrior/nbn-upgrade-map#187]
The behaviour should be updated

- ~~no arguments provided: automatically fetch next suburb~~
- ~~named arguments for state/suburb will do that specific suburb if both are provided (make sure to format input to match internal)~~
- time argument (new feature that would run program for x amount of minutes mins and keep doing suburbs)

**Comment by LukePrior** [comment]
See https://github.com/LukePrior/nbn-upgrade-map/commit/1e270f21d078417b31c9f289ea7fc0490e9a1a30 for first two

**Comment by LukePrior** [comment]
Testing a time argument now

**Comment by LukePrior** [comment]
Initial implementation here: https://github.com/LukePrior/nbn-upgrade-map/commit/970ef275fc28ac28a51c8022aed60c581d6a310d#diff-7064e9412d3433452f4affd6fe285500ff3a2a4328232d57e3e86cf437b086b4R156

Need to improve how `combined-suburbs` file is updated after each suburb so that the next is correctly found.

It takes too long as it checks every file even when we know only one has changed so should probably just fetch the existing list then append and write?

Any ideas @lyricnz

**Comment by lyricnz** [comment]
Yes, looking through all the files is a waste of time (we know exactly what has been updated).  I don't see the (real world) need for having two separate processes, and it would be way more efficient to just do it inline.  We should have a separate adhoc process, which could do the "full sync" if there was a circumstance where they got out of date, but that would only happen for non-workflow result commits.

**Comment by lyricnz** [comment]
For that matter, the progress.json file could be done the same.

**Comment by lyricnz** [comment]
Looks like you've done some of this already

**Comment by lyricnz** [comment]
Perhaps process_suburb() should be responsible for updating the output directly, and not need an external write_results_json().

**Comment by lyricnz** [comment]
In https://github.com/LukePrior/nbn-upgrade-map/pull/195 I've made the main result-processing cycle update the combined-suburbs.json and  progress.json directly.

**Comment by lyricnz** [comment]
I think this can be closed
