### ISSUE TITLE
Jordan Springs NSW - Error

### ISSUE THREAD

**Issue by Jorvanus** [LukePrior/nbn-upgrade-map#194]
Hi, this looks wrong. 

![image](https://github.com/LukePrior/nbn-upgrade-map/assets/89010934/28ae6541-0bb0-487b-ba4f-3ae6fd85efae)

**Comment by lyricnz** [comment]
Do you have a specific address that the map is showing incorrect data?  It looks like "OptiComm delivers a fibre network to this area", which is not NBN, so we don't have any data to use.

<img width="1428" alt="image" src="https://github.com/LukePrior/nbn-upgrade-map/assets/122371/7ac18e5b-dedf-4f1e-a096-843278a05cd9">

**Comment by Jorvanus** [comment]
Visually confusing, but it makes sense
