### ISSUE TITLE
Port Macquarie 2444, Lake Cathie 2445 and Wauchope 2446 

### ISSUE THREAD

**Issue by alexeiw123** [LukePrior/nbn-upgrade-map#2]
Awesome tool.
Would be awesome if we could visualise the NSW postcodes 2444, 2445 and 2446.
Thanks!

**Comment by LukePrior** [comment]
Here you go!

https://lukeprior.github.io/nbn-upgrade-map/?suburb=port-macquarie
https://lukeprior.github.io/nbn-upgrade-map/?suburb=lake-cathie
https://lukeprior.github.io/nbn-upgrade-map/?suburb=wauchope
