### ISSUE TITLE
Dependency and vulnerability scanning

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#210]
Dependabot  https://docs.github.com/en/code-security/dependabot

Code scanning https://docs.github.com/en/code-security/code-scanning

**Comment by lyricnz** [comment]
Quite a bit can be enabled via clickops in https://github.com/LukePrior/nbn-upgrade-map/nbn-upgrade-map/settings/security_analysis

**Comment by lyricnz** [comment]
I've enabled it in my fork, fwiw.  Sample config https://github.com/LukePrior/nbn-upgrade-map/compare/main...lyricnz:nbn-upgrade-map:main

**Comment by LukePrior** [comment]
I've added code scanning

**Comment by LukePrior** [comment]
Dependabot is currently useless because we don't fix the python package versions

**Comment by lyricnz** [comment]
@LukePrior can this be closed?
