### ISSUE TITLE
Create a GitHub Action to update announced dates

### ISSUE THREAD

**Issue by LukePrior** [LukePrior/nbn-upgrade-map#215]
See https://github.com/LukePrior/nbn-upgrade-map/blob/main/code/adhoc_tools.py#L92

**Comment by lyricnz** [comment]
These were updated as someone noticed in https://forums.whirlpool.net.au/thread/3w01zz89?p=31#r609

**Comment by lyricnz** [comment]
Web page format changed, breaking the scraper. Updated in https://github.com/LukePrior/nbn-upgrade-map/pull/260

**Comment by kiwisg124** [comment]
NBN has updated the suburb announcement list here:-
https://www.nbnco.com.au/residential/upgrades/more-fibre#announced-areas
Now as at 22/9/23.

**Comment by LukePrior** [comment]
I have manually updated the dates, and two new suburbs in TAS were announced.

Still need to get this automated.

**Comment by LukePrior** [comment]
Needs updating again

**Comment by LukePrior** [comment]
Updated and created a function in adhoc tools

**Comment by lyricnz** [comment]
Announced dates have been removed. This can be closed @LukePrior
