### ISSUE TITLE
Update progress.json to show oldest file

### ISSUE THREAD

**Issue by LukePrior** [LukePrior/nbn-upgrade-map#233]
will be good to keep track of how often everything get's updated

**Comment by LukePrior** [comment]
Started work here: https://github.com/LukePrior/nbn-upgrade-map/commit/0472f5a266db77df7f955753db4235b714499a7f

**Comment by lyricnz** [comment]
Where's your unit-test bro? :)

**Comment by LukePrior** [comment]
It will come :)

(making me write good code...)

**Comment by lyricnz** [comment]
I know it's your project, but maybe you should use PRs too :P

**Comment by lyricnz** [comment]
Where is this at?
