### ISSUE TITLE
Address showing as Multiple units when it is a single premise house. 

### ISSUE THREAD

**Issue by JackSterne01** [LukePrior/nbn-upgrade-map#241]
I have noticed that the FTTP Rollout has hit my area. I was advised that complex dwellings (Apartments/units) were not being done. I can see that my address is showing up as 6 Units when it is a house. just wondering if that would affect whether or not we are eligible for the fibre upgrade.

**Comment by lyricnz** [comment]
It's possible that there is misalignment between the GNAF (address database), and NBN. How does your address look on NBNco website?   Was your premises _ever_ multi-dwellings?  (either in a previous life, or knock-down rebuild?). Feel free to email me @gmail your address if you want me to look into your specific case.

**Comment by JackSterne01** [comment]
Hey Simon,
Really appreciate you getting back to me mate.
We have had a house on this lot of land for over 15 years. Just a single
house no sublet apartments or anything just a normal house. I will forward
you through an email concisely describing the issue with images for
reference. I hope this will help. Thanks simon

**Comment by JackSterne01** [comment]
My email address is ***@***.*** . I cant seem to find your email
anywhere. But if your able to send me an email, i have a detailed
explanation of the data error that i can send through.
Cheers jack

**Comment by lyricnz** [comment]
github censored your email address.  I'm mygithub-id @ gmail.com

**Comment by lyricnz** [comment]
Have received a copy of the email OP sent to their ISP.  It appears that both the GNAF database, and hence NBNco website, have multiple dwellings listed for his address.  He needs to submit a request (via his ISP) per https://www.nbnco.com.au/missingaddress to get this updated.

> If your address record requires updating or you are still unable to find your address, you’ll need to contact a [phone and internet provider](https://www.nbnco.com.au/residential/service-providers) who will contact nbn to assist in making these changes or help registering your address

**Comment by JackSterne01** [comment]
i have reached out to telstra and Aussie Broadband (Current ISP is
Tesltra). Telstra says that they are unable to make contact with NBN.
Aussie broadband has said that NBN has responded in a way that is
ignorant of the fact that our address is listed incorrectly, and that we
will need to pay to have our address upgraded to FTTP. However I am just
trying to get my address listed and recorded correctly

**Comment by lyricnz** [comment]
Suggest point your current ISP at https://www.nbnco.com.au/missingaddress and offer to send them a utility bill with your address on it.   Also https://online.nswlrs.com.au/ will demonstrate that it's a single land title.

**Comment by lyricnz** [comment]
If your ISP refuses to contact NBN on your behalf (this is 100% their responsibility), maybe you can file a complaint with NBNco.

**Comment by LukePrior** [comment]
If you run into any other issues feel free to raise them but I will close this now.
