### ISSUE TITLE
Update to GNAF 202308

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#244]
Per https://github.com/LukePrior/nbn-upgrade-map/issues/216#issuecomment-1696693277

**Comment by lyricnz** [comment]
Upstream has created a release. Should just have to run the GHA

**Comment by LukePrior** [comment]
Done

**Comment by LukePrior** [comment]
We will have to wait ~20 days for all the new addresses to be added, as we don't track what suburbs have new ones or changes and need updating but I think this is will be fine.

**Comment by lyricnz** [comment]
Yup.
