### ISSUE TITLE
(enhancement) publish a docker image containing the app

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#250]
So people who can't be bothered dealing with installing python and platform-deps can execute the code.  

_Presumably just the python part, with a volume-mount for the ./results directory._

**Comment by lyricnz** [comment]
Motivation: for no good reason, I wanted to run the code in a brand-new Fedora VM.  Had to install libpq-devel gcc and python3-devel just to be able to install the requirements.txt 
(also docker, and manually starting the DB image)

**Comment by lyricnz** [comment]
Maaaaaaybe CI could even use this, rather than running natively.  This would remove the need to install the dependencies every time...

**Comment by LukePrior** [comment]
Yeah the auto and main workflows should be able to use the Docker image, test and other workflows should keep existing processes.
