### ISSUE TITLE
(bug) Fetching/processing the announced-suburbs list generates KeyError

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#259]
```
  File "/Users/simonroberts/src/github/lyricnz/nbn-upgrade-map/code/adhoc_tools.py", line 73, in <dictcomp>
    return {data.STATES_MAP[state]: [s.title() for s in suburbs_list] for state, suburbs_list in results.items()}
KeyError: 'NSW'
```

I guess they changed the page layout a bit

**Comment by lyricnz** [comment]
get_nbn_suburb_dates() is also broken

**Comment by lyricnz** [comment]
(Unless you know of one...) It looks like there isn't a page listing all the announced suburbs, only the one with the suburbs-dates.  I'll update the adhoc code.

**Comment by lyricnz** [comment]
@LukePrior should we removed "announced" from the suburb data, and use `announced_date is not None`?

**Comment by LukePrior** [comment]
Yeah, that sounds like a good course of action

**Comment by lyricnz** [comment]
Done

**Comment by lyricnz** [comment]
Fixing https://github.com/LukePrior/nbn-upgrade-map/issues/261 in the same PR now. Sec.

**Comment by lyricnz** [comment]
@LukePrior I think I'm going to need the auto-processing stopped, so I can get this merged cleanly.  We're fighting merge conflicts with combined-suburbs.json having the "announced" field removed.
