### ISSUE TITLE
Changed meaning of FTTP_NA

### ISSUE THREAD

**Issue by LukePrior** [LukePrior/nbn-upgrade-map#286]
We have addresses not expected until 2025 now returning this so will need to incorporate the new fields and then update site to somehow use the date.

**Comment by kiwisg124** [comment]
My address which was orderable 1 December 23 now has  
"altReasonCode":"FTTP_NA
"techChangeStatus":"Committed
"programType":"On-Demand N2P SDU/MDU Simple
"targetEligibilityQuarter":"Mar 2024 
Looks like they snuck in the predictable delay.  The upgrade checker which previously showed suburb dates now gives ..
nbn is already working to make nbn Fibre to the Premises (FTTP) available to your area through another program.  https://www.nbnco.com.au/learn/technology-choice-program/online-quote

**Comment by lyricnz** [comment]
This is related to https://github.com/LukePrior/nbn-upgrade-map/issues/285
Which adds the new data to the GeoJSON files, and shows this in the map interface.
It does not, however, change the interpretation of FTTP_NA

**Comment by LukePrior** [comment]
I think this is fine now.
