### ISSUE TITLE
View historical data for a suburb

### ISSUE THREAD

**Issue by blonghong** [LukePrior/nbn-upgrade-map#288]
Would love to go back in time for my suburb and see the progress as areas were opened up to FTTP. Is there currently a way to view old data on the website that I’m missing? Would I be able to if running locally?

**Comment by LukePrior** [comment]
This data exists within the repo but with the way we store data it is not a readily available option. The best option would be to check the git history for your suburbs geojson file and download the file at each commit it was changed. You could then either modify the frontend to load all these files and implement some way of selecting them. I don't plan to add such a feature to the site currently but I am hoping to have overview level information (number of premises of each type) on a per suburb level as this data is already generated and the stats page just needs updating to use it.

**Comment by lyricnz** [comment]
I'll have a shot at this

**Comment by lyricnz** [comment]
@blonghong this is now done and deployed - check out the video at https://github.com/LukePrior/nbn-upgrade-map/pull/293#issuecomment-1796969976 for a demo
Please close this issue if this is sufficient for your usage.

**Comment by lyricnz** [comment]
@LukePrior OP posted on the PR indicating acceptance. Suggest close this issue.
