### ISSUE TITLE
add "loading" message during async loads so UI doesn't look frozen or not updating

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#295]
After https://github.com/LukePrior/nbn-upgrade-map/pull/293

**Comment by LukePrior** [comment]
related to this when the user selects a new suburb or date the dropdown menus should be disabled until the new data is loaded.

**Comment by lyricnz** [comment]
I look forward to your PR.  My javascript foo is bad.

**Comment by LukePrior** [comment]
You beat me to it :)

**Comment by LukePrior** [comment]
will need to add error handling or maybe just only show data as far back as the format is same.

**Comment by lyricnz** [comment]
I figure we should try and make the code backward compatible. I haven't noticed any issues yet

**Comment by LukePrior** [comment]
I think I ran into one when I selected the oldest for Blog Bli
