### ISSUE TITLE
Occasional issue when selecting older data in map view

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#297]
From #293 #295 etc.

It's sometimes possible to see errors when navigating old history. For example, selecting the second-oldest Bli-Bli date gave me this:

<img width="1114" alt="image" src="https://github.com/LukePrior/nbn-upgrade-map/assets/122371/2fc37209-5d2e-44ce-b302-9c3f8a6f7cc9">

The 404 URL is
https://raw.githubusercontent.com/LukePrior/nbn-upgrade-map/7473d0340b2c0903276f1ecce2e3a10c3a35061f/results/QLD/bli-bli.geojson

And the commits URL is
https://api.github.com/repos/LukePrior/nbn-upgrade-map/commits?path=results/QLD/bli-bli.geojson
which does include 7473d0340b2c0903276f1ecce2e3a10c3a35061f

Are we using the wrong field in the JSON?  (maybe commits direct to master, vs commits on a PR??)

**Comment by lyricnz** [comment]
The history page for that suburb https://github.com/LukePrior/nbn-upgrade-map/commits/main/results/QLD/bli-bli.geojson also shows the commit, but it looks like it _deleted_ all these files

https://github.com/LukePrior/nbn-upgrade-map/commit/7473d0340b2c0903276f1ecce2e3a10c3a35061f

Maybe we need to special-case this sha out of the list?  I don't know of another way to identify such case.

**Comment by LukePrior** [comment]
Doesn't seem to have resolved, further investigation required.

**Comment by LukePrior** [comment]
Now it's fixed
