### ISSUE TITLE
Maleny / North Maleny (4552)

### ISSUE THREAD

**Issue by GaryFlynn** [LukePrior/nbn-upgrade-map#3]
This is a really useful and awesome tool, thanks!

Is there any possibility of adding Maleny and North Maleny to the map (4552)?

**Comment by LukePrior** [comment]
Done: 

https://lukeprior.github.io/nbn-upgrade-map/?suburb=maleny
https://lukeprior.github.io/nbn-upgrade-map/?suburb=north-maleny
