### ISSUE TITLE
Why is Bli Bli QLD missing the latest data? 

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#315]
https://lukeprior.github.io/nbn-upgrade-map/?suburb=bli-bli&state=QLD&commit=main

<img width="324" alt="image" src="https://github.com/LukePrior/nbn-upgrade-map/assets/122371/541a1b7b-32bb-4130-8035-97c25a30abc4">

vs
 
https://github.com/LukePrior/nbn-upgrade-map/commits/main/results/QLD/bli-bli.geojson

<img width="729" alt="image" src="https://github.com/LukePrior/nbn-upgrade-map/assets/122371/1791dd85-9017-4667-86dc-7c88c59fd533">

**Comment by lyricnz** [comment]
Is this related to https://github.com/LukePrior/nbn-upgrade-map/pull/313 ?

**Comment by LukePrior** [comment]
Yes once it updates in next few days it will go back to showing the latest.

**Comment by LukePrior** [comment]
All cases of this should be fixed now I believe.
