### ISSUE TITLE
Add loc id to bubbles.

### ISSUE THREAD

**Issue by majibow** [LukePrior/nbn-upgrade-map#319]
Add loc id to bubbles. The info is already there in the geojson, but is no displayed on the map site. Please save me the trouble of sifting through the raw data and include it in the bubbles.

**Comment by LukePrior** [comment]
Hi,

Feel free to open a PR modifying the front-end, should just be a simple addition.

Otherwise I'll look into adding it next week.

**Comment by majibow** [comment]
Hi thanks, done :)

See comment in PR #320
