### ISSUE TITLE
Representation of "You will soon need to transition to FTTP"

### ISSUE THREAD

**Issue by cmcqueen** [LukePrior/nbn-upgrade-map#327]
I've found some addresses on the map which are shown as FTTP, but the NBN web site describes them as

> Technology used in your connection
> nbn® Fibre to the Node (FTTN) has been used in your connection to the nbn network.

and says

> We’re planning to change your nbn technology.
> You will soon need to transition your existing nbn powered plan to a new plan based on nbn® Fibre to the Premises (FTTP). Your phone and internet service provider will be in touch to guide you through the process.

For example, 11 Hales Ct, West Wodonga, VIC 3690

This appears to pertain to addresses that your map describes as "Tech Change Status: Eligible To Order".

**Comment by LukePrior** [comment]
I'm not sure but this is the data we record

```
   "properties": {
    "name": "11 HALES COURT WEST WODONGA 3690",
    "locID": "LOC000017715714",
    "tech": "FTTP",
    "upgrade": "FTTN_CT",
    "gnaf_pid": "GAVIC421564906",
    "tech_change_status": "Eligible To Order",
    "program_type": "On-Demand N2P SDU/MDU Simple",
    "target_eligibility_quarter": "NA"
   }
```

So I suspect both technologies have been installed at the premises but the FTTN hasn't yet been disconnected.

**Comment by LukePrior** [comment]
The logic we use on the site can be found here: https://github.com/LukePrior/nbn-upgrade-map/blob/main/site/index.html#L174

Not sure if there is a way to separate this case out with the data we have, would need to investigate.

**Comment by cmcqueen** [comment]
I'm not sure how you get `"tech": "FTTP"`. The raw data from nbnco.com.au is

```
{"timestamp":1709081614778,"servingArea":{"csaId":"CSA200000000008","techType":"FTTN","serviceType":"Fixed line","serviceStatus":"available","serviceCategory":"brownfields","rfsMessage":"Jan 2017","description":"Wodonga"},"addressDetail":{"id":"LOC000017715714","latitude":-36.12316,"longitude":146.851036,"reasonCode":"FTTN_CT","altReasonCode":"FTTP_SA","techChangeStatus":"Eligible To Order","programType":"On-Demand N2P SDU/MDU Simple","targetEligibilityQuarter":"NA","previousTechChangeStatus":"NA","patChangeDate":"Dec 2023","patChangeStatus":true,"techFlip":"No","serviceType":"Fixed line","serviceStatus":"available","mduFibreEligibility":false,"disconnectionStatus":"PAST","disconnectionDate":"Jul 2018","techType":"FTTN","formattedAddress":"11 HALES CT WEST WODONGA VIC 3690 Australia","address1":"11 Hales Ct","address2":"West Wodonga VIC 3690 Australia","locality":"West Wodonga","statusMessage":"connected-true","frustrated":false,"zeroBuildCost":true,"wp1DisconnectionDate":"12 November 2018","wp1DisconnectionStatus":"PAST","wp2DisconnectionDate":"29 April 2019","wp2DisconnectionStatus":"PAST","wp3DisconnectionDate":"31 May 2019","wp3DisconnectionStatus":"PAST","wp4DisconnectionDate":"30 September 2019","wp4DisconnectionStatus":"PAST","speedTierAvailability":true,"eec":1,"forecastedRTC":false,"coatChangeReason":"on-demand","cbdpricing":true,"ee":true,"TC2SMM":true}}
```

which contains `"techType":"FTTN"`.

**Comment by lyricnz** [comment]
This circumstance looks similar to the FW->FTTN one #350 , in that NBN is reporting upgrade=FTTN_CT and tech=FTTP to mean that you currently have FTTN but are eligible to order.

```
    "tech": "FTTP",
    "upgrade": "FTTN_CT",
    "tech_change_status": "Eligible To Order",
```

**Comment by lyricnz** [comment]
@LukePrior can we assume that all instances of upgrade=XXX_CT and tech=OTHER really mean that they currently have XXX and have an upgrade to OTHER(ish) available?  This matches the FW/WIRELESS case, as well as this one.

I think NBNco are counting those as FTTP for the purpose of politics etc, when they're not actually connected to such.

**Comment by lyricnz** [comment]
There are currently 173580 addresses with _CT as their upgrade. Total tech breakdown:

```
Counter({'NULL_NA': 296265171,
         'FTTP_SA': 100317074,
         'FTTP_NA': 65849684,
         'UNKNOWN': 46765587,
         'SAT_CT': 100829,
         'FW_CT': 75443,
         'FW_NA': 55242,
         'FTTN_CT': 24729,
         'FTTN_NA': 290,
         'FTTC_NA': 263,
         'FTTN_SA': 133,
         'FTTC_CT': 40,
         'FTTB_NA': 39})
```

**Comment by lyricnz** [comment]
For the upgrade=_CT ones, here is breakdown of the corresponding tech 

```
Counter({'FTTP': 167559,
         'WIRELESS': 4526,
         'FTTC': 1181,
         'FTTN': 310,
         'SATELLITE': 3,
         'NULL': 1})
```

Which means if we apply this logic, those numbers will all go down by those amounts, and the corresponding others will go up:

```
Counter({'FTTN_CT': 162004,
         'SAT_CT': 4634,
         'FTTC_CT': 3980,
         'FW_CT': 2503,
         'FTTB_CT': 341,
         'HFC_CT': 118})
```

**Comment by lyricnz** [comment]
This is how the migration would look:

<img width="739" alt="image" src="https://github.com/LukePrior/nbn-upgrade-map/assets/122371/949739b3-efaa-4bc7-b872-211f29f88a0e">

**Comment by cmcqueen** [comment]
It looks good to me.

If you enter 11 Hales Ct on the NBN web site, and compare it to 9 Hales Ct, the NBN web site describes them differently for some reason, even though they're both currently FTTN. But in any case, the new representation of 11 Hales Ct in the Luke Prior maps is more accurate now than it was before, so that is good.

**Comment by lyricnz** [comment]
@cmcqueen can you close this issue then please?
