### ISSUE TITLE
Bot has stopped, and is no longer crawling. 

### ISSUE THREAD

**Issue by Jorvanus** [LukePrior/nbn-upgrade-map#328]
Bot has stopped, and is no longer crawling.

**Comment by lyricnz** [comment]
It was stopped a few days ago because someone noticed we are losing addresses.
https://github.com/LukePrior/nbn-upgrade-map/issues/326#issuecomment-1951680109

**Comment by Jorvanus** [comment]
> It was stopped a few days ago because someone noticed we are losing addresses. [#326 (comment)]

Yes, that was me.  Wasn't sure the fact that it was stopped was intentional or not.

**Comment by LukePrior** [comment]
See other thread
