### ISSUE TITLE
Option for more verbose output/debugging?

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#35]
This script takes a long time to run. It would be nice if it was capable of outputting some progress information, or details about what it's doing.  Also, error messages if suburb/state were invalid or not found etc.

**Comment by LukePrior** [comment]
The execution time for the script is dependent on the suburb in regards to the number of addresses it needs to check with NBN. The script is configured to maintain 20 simultaneous requests, while increasing this amount it is possible it increases the strain on the NBN API to a point where I'm not comfortable.

 The script was hacked together in a day so as you note it unfortunately lacks any debugging or sufficient documentation/testing. I will hopefully get around to improving this eventually but given my limited time for this project it's not an immediate priority however I would be happy to accept any pull requests incorporating such changes.

**Comment by lyricnz** [comment]
Yeah man, I understand how it is.   Maybe I'll find the time someday too :)

**Comment by lyricnz** [comment]
Thanks for your efforts, and contributing :)

**Comment by lyricnz** [comment]
https://github.com/LukePrior/nbn-upgrade-map/pull/40

**Comment by LukePrior** [comment]
Note to self: would be good to get some indication of progress while going through the NBN API calls. Investigate checking how many threads have completed.

**Comment by lyricnz** [comment]
Yup, I agree, and it was the primary reason for the suggestion (besides the silent failure with bad parameters).  I thought to leave this until after/if we resolve caching.

**Comment by lyricnz** [comment]
Added progress indicator in https://github.com/LukePrior/nbn-upgrade-map/pull/54
