### ISSUE TITLE
Historical Percent breakdown busted

### ISSUE THREAD

**Issue by Jorvanus** [LukePrior/nbn-upgrade-map#354]
![image](https://github.com/LukePrior/nbn-upgrade-map/assets/89010934/bddb4c7a-05b2-406f-b0ae-34e616813cf4)

![image](https://github.com/LukePrior/nbn-upgrade-map/assets/89010934/51aef596-f86f-46fd-b3ae-718f815c9b61)

**Comment by LukePrior** [comment]
I think it's because a new label of FW has appeared

**Comment by lyricnz** [comment]
I'll have a look

**Comment by lyricnz** [comment]
Fixed https://lukeprior.github.io/nbn-upgrade-map/stats
