### ISSUE TITLE
Dynamic Legend Incorrect Values

### ISSUE THREAD

**Issue by LukePrior** [LukePrior/nbn-upgrade-map#362]
There seems to be an issue where FTTN is shown as FTTC in the legend.

**Comment by lyricnz** [comment]
Example?

**Comment by LukePrior** [comment]
Oh sorry looks like the image didn't upload here we go.

But yeah updating it to show all the different cases would be good.

https://lukeprior.github.io/nbn-upgrade-map/?suburb=adamstown&state=NSW&commit=main

![Screenshot_20240520_175831_Chrome](https://github.com/LukePrior/nbn-upgrade-map/assets/22492406/160b1274-a45b-4500-8fca-3bec858758a9)

**Comment by lyricnz** [comment]
Cut and paste bug 

![image](https://github.com/LukePrior/nbn-upgrade-map/assets/122371/155f7970-8d79-4ccc-ac1f-62956bb48612)

**Comment by lyricnz** [comment]
Fix fix it along with #361

**Comment by lyricnz** [comment]
From #361 

<img width="709" alt="image" src="https://github.com/LukePrior/nbn-upgrade-map/assets/122371/5e3a52c9-653d-42b3-bfcd-cdd5837df178">

**Comment by lyricnz** [comment]
Fixed in #366

**Comment by lyricnz** [comment]
@LukePrior I think this can be closed
