### ISSUE TITLE
Automatic Runs Getting Cancelled

### ISSUE THREAD

**Issue by LukePrior** [LukePrior/nbn-upgrade-map#374]
https://github.com/LukePrior/nbn-upgrade-map/actions/runs/9278998685
https://github.com/LukePrior/nbn-upgrade-map/actions/runs/9293841297

**Comment by LukePrior** [comment]
Seems to occur during checkout

https://github.com/LukePrior/nbn-upgrade-map/actions/runs/9296576831/job/25585301074

**Comment by lyricnz** [comment]
Does it happen often?  We can't do much if "git fetch" fails

**Comment by LukePrior** [comment]
Seems to be every few hours, not sure why it would be failing with such frequency, is the got history too large or something...

**Comment by lyricnz** [comment]
Hasn't happened since the few above - maybe github was just having a bad day.

**Comment by LukePrior** [comment]
Yeah hopefully that's just the case. Will close for now.
