### ISSUE TITLE
Generate HTML page for local hosting of website

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#379]
Per #378 and #34

**Comment by LukePrior** [comment]
Yeah I was having a think about this, not sure if it makes sense to setup the website as a proper project and then have different build targets for prod and local with accompanying update to GitHub actions to build and push changes.

**Comment by lyricnz** [comment]
For now, I'll just make an adhoc task which makes a local version of index.html/main.js (but user will still need to launch with CORS disabled)

**Comment by lyricnz** [comment]
See the PR @LukePrior
