### ISSUE TITLE
Some addresses are showing orange as FTTC although FTTP is apparently connected (and FTTC->FTTP upgrades generally available in the area)

### ISSUE THREAD

**Issue by trs80** [LukePrior/nbn-upgrade-map#384]
Eg LOC000038973474 "reasonCode":"FTTP_CT","altReasonCode":"FTTC_CT","techChangeStatus":"New Tech Connected"
vs LOC000058374654 "reasonCode":"FTTC_CT","altReasonCode":"FTTP_SA","techChangeStatus":"Eligible to Order"
and LOC000079861379 "reasonCode":"FTTP_CT","altReasonCode":"NULL_NA","techChangeStatus":"Previous Tech Disconnected"

**Comment by lyricnz** [comment]
You couldn't tell us the suburb? 

```
   "properties": {
    "name": "39 NINGALOO WAY THORNLIE 6108",
    "locID": "LOC000038973474",
    "tech": "FTTC",
    "upgrade": "FTTP",
    "gnaf_pid": "GAWA_146801070",
    "tech_change_status": "New Tech Connected"
   }
```

Even the NBNco website seems confused about this:

<img width="987" alt="image" src="https://github.com/user-attachments/assets/043e0094-a769-4426-a3f2-7b826fbeec99">

**Comment by lyricnz** [comment]
```
   "properties": {
    "name": "1 PENDER COURT THORNLIE 6108",
    "locID": "LOC000058374654",
    "tech": "FTTC",
    "upgrade": "FTTP_SA",
    "gnaf_pid": "GAWA_147006557",
    "tech_change_status": "Eligible to Order"
   }
```

<img width="806" alt="image" src="https://github.com/user-attachments/assets/2be30f0d-6c85-4e67-9c76-c461df72059e">

**Comment by lyricnz** [comment]
```
   "properties": {
    "name": "12 CAMDEN COURT THORNLIE 6108",
    "locID": "LOC000079861379",
    "tech": "FTTP",
    "upgrade": "NULL_NA",
    "gnaf_pid": "GAWA_146798813",
    "tech_change_status": "Previous Tech Disconnected"
   }
```

<img width="543" alt="image" src="https://github.com/user-attachments/assets/e9ab2a63-559b-4286-8ad0-980138cc22c8">

**Comment by trs80** [comment]
> You couldn't tell us the suburb?

I mean you can get it from the LOCIDs but fair, I was just being lazy

> ```
>    "properties": {
>     "name": "39 NINGALOO WAY THORNLIE 6108",
>     "locID": "LOC000038973474",
>     "tech": "FTTC",
>     "upgrade": "FTTP",
>     "gnaf_pid": "GAWA_146801070",
>     "tech_change_status": "New Tech Connected"
>    }
> ```
> 
> Even the NBNco website seems confused about this:

Yeah that's an odd result from their side. But I guess the FTTC could still be active and they have another service now on FTTP?

> **I don't know how we can plot tech=FTTC anything except orange?**

I mean, upgrade=FTTP surely means FTTP upgrade is available. I was going to suggest adding another line to https://github.com/LukePrior/nbn-upgrade-map/blob/main/code/main.py#L33 but https://github.com/LukePrior/nbn-upgrade-map/blob/main/code/main.py#L84 only looks at altReasonCode, the differentiator is in reasonCode which isn't checked anywhere at the moment.

**Comment by LukePrior** [comment]
Hi @trs80 I've pushed an update, please let me know if there are any cases where this is still being incorrectly displayed.

**Comment by LukePrior** [comment]
Closing due to lack of reply
