### ISSUE TITLE
Westlake, Riverhills, Middle Park, Mount Ommaney, Jindalee, Jamboree Heights. QLD

### ISSUE THREAD

**Issue by jebbusjebbus** [LukePrior/nbn-upgrade-map#39]
if its not too much trouble to add these as well

**Comment by lyricnz** [comment]
Already done:
- Riverhills
- Middle Park

To Do:
- Westlake
- Mount Ommaney
- Jindalee
- Jamboree Heights

**Comment by lyricnz** [comment]
Processing is currently up to the Cs in QLD (for suburbs listed for upgrade)
