### ISSUE TITLE
Glenwood NSW

### ISSUE THREAD

**Issue by peter-mc** [LukePrior/nbn-upgrade-map#4]
Can you please add Glenwood NSW 2768

**Comment by LukePrior** [comment]
Sure here you go: https://lukeprior.github.io/nbn-upgrade-map/?suburb=glenwood

**Comment by peter-mc** [comment]
> Sure here you go: https://lukeprior.github.io/nbn-upgrade-map/?suburb=glenwood

Great job, thanks Luke, I do notice the Glenwood suburb isn't in the drop down list yet though..

**Comment by LukePrior** [comment]
> Great job, thanks Luke, I do notice the Glenwood suburb isn't in the drop down list yet though.

GitHub has quite aggressive caching of the list used to generate the dropdown menu so it can take a few minutes for the new copy to be served.

**Comment by peter-mc** [comment]
working now, thanks again :)

**Comment by peter-mc** [comment]
I see you have started sorting the suburbs by state now, and Glenwood NSW 2768 is still listed in the QLD group for some reason...

Any chance you could also add Bella Vista NSW 2153 and North Rocks NSW 2151 ??

**Comment by LukePrior** [comment]
Thanks for the catch, as you've noticed I've needed to sort things into states to avoid duplicate suburb names and that has come with some reorganisation of the website.

If you could open a new issue for the suburbs that would be great.

**Comment by peter-mc** [comment]
nw - yeah, Glenwood was one of those in both states :)

new request opened
