### ISSUE TITLE
Cloudflare - Invalid SSL certificate

### ISSUE THREAD

**Issue by ozmule** [LukePrior/nbn-upgrade-map#406]
Currently getting Cloudflare Invalid SSL certificate error

<img width="673" alt="{C9F984BA-0200-4F9E-B1F4-879213E927DF}" src="https://github.com/user-attachments/assets/90acf48f-ecab-462d-ab40-5ed7e8ae9735">

**Comment by lyricnz** [comment]
Yup
<img width="557" alt="image" src="https://github.com/user-attachments/assets/40dc95d2-1c4d-4448-82a3-1b37ef5b6fa2">

**Comment by LukePrior** [comment]
This was the issue: fixed for now but looking for a long term solution: https://gist.github.com/zbeekman/ac6eeb41ea7980f410959b13416d74c9#gistcomment-2815743
