### ISSUE TITLE
Bathurst

### ISSUE THREAD

**Issue by LukePrior** [LukePrior/nbn-upgrade-map#49]
Bathurst
West Bathurst
Windradyne
Mount Pleasant
Robin Hill
Kelso
Laffing Waters
Raglan
South Bathurst
Gormans Hill
Mount Panorama

**Comment by lyricnz** [comment]
Most of these are done:

Checking: Bathurst
  Found BATHURST NSW
Checking: West Bathurst
  Found WEST BATHURST NSW
Checking: Windradyne
  Found WINDRADYNE NSW
Checking: Mount Pleasant
  Found MOUNT PLEASANT NSW
Checking: Robin Hill
Checking: Kelso
  Found KELSO NSW
Checking: Laffing Waters
Checking: Raglan
  Found RAGLAN NSW
Checking: South Bathurst
  Found SOUTH BATHURST NSW
Checking: Gormans Hill
Checking: Mount Panorama
