### ISSUE TITLE
Change to gnafloader:latest breaks schema in SQL query

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#57]
This commit https://github.com/LukePrior/nbn-upgrade-map/commit/576d61b00a1d15f8858ccd5c0940a5cae1cf76d5 updated the docker image to use :latest which now uses a different schema name.

The PR https://github.com/LukePrior/nbn-upgrade-map/pull/56 fixes this (along with optionally adding an index to the DB to speed up subsequent runs)

**Comment by LukePrior** [comment]
Cheers
