### ISSUE TITLE
Tweed Heads 2485

### ISSUE THREAD

**Issue by RossKerker** [LukePrior/nbn-upgrade-map#6]
Would be great to have this suburb added

**Comment by LukePrior** [comment]
Sure here you go: https://lukeprior.github.io/nbn-upgrade-map/?suburb=tweed-heads

**Comment by RossKerker** [comment]
Thanks. Interesting that "Tweed Heads" is in the announced suburbs lost no less than 7 times, yet is almost entirely red with a couple existing FTTP's
