### ISSUE TITLE
Add Chapman, ACT. 2611

### ISSUE THREAD

**Issue by Roving-Ronin** [LukePrior/nbn-upgrade-map#60]
Thanks in advance.

**Comment by Roving-Ronin** [comment]
Hi @LukePrior, just wondering if this would be possible? Currently only 1 suburb (at the southern tip) available for ACT.

Also the 2nd suburb you ever added (Goulburn, NSW), just went to check it and noticed that its dissappeared from the map / pull down list?

Thanks, Justin

**Comment by LukePrior** [comment]
I'm working my way through all of them could take a week or two

Progress vs Listed Suburbs:
  ACT: 1 / 18  (5.6%)
  NSW: 310 / 473  (65.5%)
  NT: 0 / 13  (0.0%)
  QLD: 3 / 386  (0.8%)
  SA: 0 / 151  (0.0%)
  TAS: 0 / 31  (0.0%)
  VIC: 2 / 247  (0.8%)
  WA: 0 / 224  (0.0%)
  TOTAL: 316 / 1543  (20.5%)

**Comment by lyricnz** [comment]
I manually processed the 18 ACT suburbs that are on "the list".  FWIW Chapman isn't on the list. 
https://github.com/LukePrior/nbn-upgrade-map/tree/main/results/ACT

**Comment by Roving-Ronin** [comment]
@lyricnz Dóh.. thought it was, my bad. Just rechecked and noticed fyi that "O’Connor" is on the announcement list, but not on your list.

**Comment by lyricnz** [comment]
Hi @Roving-Ronin . Can you provide a link to the announced suburbs that include O'Conner?  The latest press release I can see is https://www.nbnco.com.au/corporate-information/media-centre/media-statements/one-million-additional-homes-and-businesses-to-become-eligible-for-full-fibre
Which doesn't include  O'Conner...

**Comment by Roving-Ronin** [comment]
@lyricnz see the section at the bottom of this article. https://www.nbnco.com.au/corporate-information/media-centre/media-statements/300000-more-homes-and-businesses-to-become-eligible-for-nbn-fibre-upgrade-by-ordering-selected-higher-speed-plans

**Comment by LukePrior** [comment]
added
