### ISSUE TITLE
Results script overwrites last modified date

### ISSUE THREAD

**Issue by LukePrior** [LukePrior/nbn-upgrade-map#68]
This happens when using GitHub Actions.

Note to self: look into how I did it with mortgage manager.

**Comment by lyricnz** [comment]
Last modified date of the results.json itself or the results-file dates within that file?

FWIW I just PR a change to that script https://github.com/LukePrior/nbn-upgrade-map/issues/70

**Comment by LukePrior** [comment]
The dates for each suburb within the file.

**Comment by lyricnz** [comment]
Is the git checkout (in GHA) not preserving the file dates?   When I checkout here, and run results.py the file-dates are accurately represented in the results.json (vs the 30-05 which is in the checkout):

```
diff --git a/results/results.json b/results/results.json
index 34804d6..ebe5624 100644
--- a/results/results.json
+++ b/results/results.json
@@ -509,7 +509,7 @@
             "state": "NSW",
             "name": "White Rock",
             "file": "white-rock",
-            "date": "30-05-2023"
+            "date": "29-05-2023"
         },
         {
             "internal": "WINDRADYNE",
@@ -537,7 +537,7 @@
             "state": "QLD",
             "name": "Inala",
             "file": "inala",
-            "date": "30-05-2023"
+            "date": "29-05-2023"
         },
         {
             "internal": "SOMERVILLE",
```

**Comment by LukePrior** [comment]
> Is the git checkout (in GHA) not preserving the file dates?

Yeah, I believe this must be the issue.

**Comment by lyricnz** [comment]
Try actions/checkout@v3 ?

**Comment by lyricnz** [comment]
I'm not sure we can rely on the file-stamps anyway?
https://archive.kernel.org/oldwiki/git.wiki.kernel.org/index.php/Git_FAQ.html#Why_isn.27t_Git_preserving_modification_time_on_files.3F

**Comment by lyricnz** [comment]
I suspect we should add some metadata to the geojson describing when it was generated?

**Comment by LukePrior** [comment]
I believe how I've done it recently is check the got history for a particular file and extract the date from the last commit affecting said file.

**Comment by lyricnz** [comment]
I've just been reading the RFC, and it's not super clear. There used to be a "crs" thing you could put some metadata into, but that's not in current version.  We could:
1) add arbitrary top-level key:value eg `"generated_date": "1-2-3",` - this doesn't seem to bother https://geojsonlint.com/
2) add a fake geometry object and parse it's label etc for the date.

**Comment by lyricnz** [comment]
Right now, all the files are today/yesterday, so there's no big deal in doing a "day 1" reset, and adding the metadata to all results.

**Comment by lyricnz** [comment]
Might as well include the state+suburb in the metadata too.

**Comment by lyricnz** [comment]
PR to include the generated date when creating geojson files, and use that date when generating results.json
https://github.com/LukePrior/nbn-upgrade-map/pull/74
