### ISSUE TITLE
Commits cause lots of failed GHA builds

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#69]
See https://github.com/LukePrior/nbn-upgrade-map/commits/main

<img width="637" alt="image" src="https://github.com/LukePrior/nbn-upgrade-map/assets/122371/20016fab-ce5d-43e0-9608-61fe68023d13">

Looks like the auto-build is doing a commit, and triggering another build (besides the one it means to).  Perhaps a filter to prevent the other build running.

**Comment by LukePrior** [comment]
Ok I think this should be fixed
