### ISSUE TITLE
Usage text is unclear regarding DB index creation

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#73]
The help text says
`  -i, --create_index    Whether to add an index to the DB to help speed up queries`
But the index is created by default, and `-i` turns it OFF

**Comment by LukePrior** [comment]
'Whether to disable adding an index to the DB to help speed up queries (only used for GitHub Actions)',

**Comment by LukePrior** [comment]
tbh this could probably be made even clearer so suggestions welcome
