### ISSUE TITLE
"NULL" tech types in output

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#76]
INFO Tally of tech types: Counter({'FTTN': 2305, 'FTTP': 916, None: 122, 'WIRELESS': 71, 'SATELLITE': 10, 'NULL': 9})

<img width="168" alt="image" src="https://github.com/LukePrior/nbn-upgrade-map/assets/122371/9a6a383e-956c-4c3d-884a-781622b6007c">

**Comment by LukePrior** [comment]
I guess should we include addresses where we can't determine the NBN tech (i.e. NULL)?

**Comment by lyricnz** [comment]
I think the NULL is coming back from the NBNco API.  If it was a python unset, it would be None.   The one in Somerville, VIC actually looks like a carpark.

3 EDWARD STREET SOMERVILLE 3912
<img width="1186" alt="image" src="https://github.com/LukePrior/nbn-upgrade-map/assets/122371/8e018795-f843-4a72-a8c1-d64571632250">

**Comment by lyricnz** [comment]
I think "NULL" is as good as we're going to get. That's what's coming from the API.
