### ISSUE TITLE
Maybe results files should be formatted + sorted?

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#77]
While this would make the files a bit larger, it would make the changelog/history of the files more readable (rather than all being on one line).

**Comment by LukePrior** [comment]
Yeah I considered that and only concern was file size as you mentioned. If the increase isn't too large I say we go for it.

**Comment by lyricnz** [comment]
Looks like file size is about doubled.  Before and after.

```
❯ ls -l results/VIC/somerville.geojson
-rw-r--r--@ 1 simonroberts  staff  1339151 30 May 15:37 results/VIC/somerville.geojson
❯ ls -l results/VIC/somerville.geojson
-rw-r--r--@ 1 simonroberts  staff  2747383 30 May 15:37 results/VIC/somerville.geojson
```

**Comment by lyricnz** [comment]
That was with indent=4.  With indent=1
```
❯ ls -l results/VIC/somerville.geojson
-rw-r--r--@ 1 simonroberts  staff  1727014 30 May 15:39 results/VIC/somerville.geojson
```

**Comment by lyricnz** [comment]
Done
https://github.com/LukePrior/nbn-upgrade-map/pull/78
https://github.com/LukePrior/nbn-upgrade-map/pull/79

**Comment by lyricnz** [comment]
and https://github.com/LukePrior/nbn-upgrade-map/pull/80
