### ISSUE TITLE
a few suburbs have disappeared

### ISSUE THREAD

**Issue by peter-mc** [LukePrior/nbn-upgrade-map#83]
hi Luke

I notice all the suburbs around me (that you did include in your map originally) have disappeared from both the dropdown and the map..

Can you please have a look and reinstate them - we are currently waiting for the upgrade, fibre has been pulled, puts cleared etc..

The local suburbs around here that have gone missing are (at least) Glenwood, Kellyville, maybe more...

**Comment by LukePrior** [comment]
Hi Peter as part of the improvements me and Simon have been working on some of the suburbs have been removed as the code didn't fully correctly scrape them. That issue has now been resolved and suburbs are beginning to get automatically re-added.

**Comment by peter-mc** [comment]
thanks Luke

**Comment by lyricnz** [comment]
FYI - current progress vs the "listed for upgrade" suburbs, and all suburbs in Australia.

```
Progress vs Listed Suburbs:
  ACT: 1 / 18  (5.6%)
  NSW: 124 / 473  (26.2%)
  NT: 0 / 13  (0.0%)
  QLD: 3 / 386  (0.8%)
  SA: 0 / 151  (0.0%)
  TAS: 0 / 31  (0.0%)
  VIC: 2 / 247  (0.8%)
  WA: 0 / 224  (0.0%)
  TOTAL: 130 / 1543  (8.4%)
Progress vs All Suburbs:
  ACT: 1 / 134  (0.7%)
  NSW: 126 / 4396  (2.9%)
  NT: 0 / 269  (0.0%)
  QLD: 3 / 3151  (0.1%)
  SA: 0 / 1864  (0.0%)
  TAS: 0 / 757  (0.0%)
  VIC: 2 / 2908  (0.1%)
  WA: 0 / 1617  (0.0%)
  TOTAL: 132 / 15096  (0.9%)
```

**Comment by lyricnz** [comment]
Current progress can be viewed by looking at the "Run results" step of the latest auto-suburb action

1. Go to https://github.com/LukePrior/nbn-upgrade-map/actions/workflows/auto.yml
2. Click on the last green job
3. Click on the box with the green checkbox
4. Click on the "run results" step

**Comment by lyricnz** [comment]
@peter-mc which suburbs?  are these processed now?  (all of NSW on the "FTTP upgrade list" has been completed)

(if so, can this issue be closed?)

**Comment by peter-mc** [comment]
hi Simon,

yes please close the missing suburbs are now back

thanks
Petre
