### ISSUE TITLE
Support Rechecking Suburbs

### ISSUE THREAD

**Issue by LukePrior** [LukePrior/nbn-upgrade-map#84]
From some very rough estimations it seems that all the announced suburbs will be processed within 3 weeks.

Once that is done the oldest suburbs should get updated if they are X weeks old or more.

There isn't currently any such functionality for this. We could also scan suburbs which haven't been announced if that is of interest to people.

**Comment by lyricnz** [comment]
After all the _missing_ suburbs are processed, maybe a second pass can look at the date of the last generation (now it's embedded), and if it's "too old" refresh it.

**Comment by shanelord01** [comment]
Hi - just had my address move from FTTP_NA to FTTP_SA over the weekend (along with all of my neighbours) but the map hasn't updated. https://lukeprior.github.io/nbn-upgrade-map/?suburb=kellyville&state=NSW

Is there any way to refresh it?

**Comment by lyricnz** [comment]
Idea: load the old output file, to create gnaf_pid -> loc_id cache.  This will halve the number of NBN requests for something that should be pretty-much fixed.

**Comment by lyricnz** [comment]
@shanelord01 suburbs should be reprocessed eventually, but there's a lot of addresses in Australia, it takes a long time (we haven't finished the first cycle yet - currently 68%)

**Comment by lyricnz** [comment]
I'll run it manually on my PC now

**Comment by shanelord01** [comment]
Hi @lyricnz @LukePrior if a "node" (ie an agent running separately from the main server that just ran distributed queries against the NBN API then reported back) was available that I could spin up in docker easily, I'd be happy to spin some servers up in Linode to help out.

**Comment by lyricnz** [comment]
We could do that, but (a) it's still pretty slow, (b) we don't want to DDoS the NBN API (or get their attention) - the process already does 10 threads in parallel. 

My laptop+internet shut down yesterday while this was running (power was off for renovations). Will restart it now.

**Comment by lyricnz** [comment]
```
python ./code/main.py --suburb kellyville --state nsw --progress 
2023-07-15 08:30:25,369 INFO MainThread Creating DB index...
2023-07-15 08:30:25,376 INFO MainThread Skipping index creation as already exists
2023-07-15 08:30:25,441 INFO MainThread Fetching all addresses for Kellyville, NSW
2023-07-15 08:30:25,661 INFO MainThread Fetched 10300 addresses from database
2023-07-15 08:30:25,699 INFO MainThread Loaded 9867 addresses from output file
2023-07-15 08:30:25,701 INFO MainThread Submitting 10300 requests to add NBNco data...
2023-07-15 08:31:59,074 WARNING nbn_9 Error fetching NBN data for 3 WAKEFIELD RISE KELLYVILLE 2155: Expecting value: line 1 column 1 (char 0)
Progress: |███████████████████████████-----------------------| 55.1% Complete
```

**Comment by lyricnz** [comment]
I think this can be closed
