### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by LukePrior** [LukePrior/nbn-upgrade-map#85]
The README needs updating to reflect the recent codebase changes especially in regards to the running locally section.

See https://github.com/LukePrior/nbn-upgrade-map/issues/34#issuecomment-1558447907

**Comment by lyricnz** [comment]
Maybe there is a better way to enable local viewing?  Maybe a version of the HTML that uses relative path (not absolute url) the run it in a local docker container to avoid the CORS stuff?

```shell
# remove hardcoded URL prefix
sed -i 's#https://raw.githubusercontent.com/LukePrior/nbn-upgrade-map/main/##' index.html

# run local webserver exposing .
docker run -it --rm -d -p 8080:80 -v .:/usr/share/nginx/html --name web nginx
```

**Comment by lyricnz** [comment]
Maybe also mention a little bit of detail about how suburbs are selected and processed, so people will understand the update-cycle.  TOTAL: 130 / 1543  (8.4%)

**Comment by lyricnz** [comment]
I think README is good enough now

**Comment by LukePrior** [comment]
Agreed
