### ISSUE TITLE
Linters and auto-formatters?

### ISSUE THREAD

**Issue by lyricnz** [LukePrior/nbn-upgrade-map#90]
Maybe Black (very opinionated)
https://black.readthedocs.io/en/stable/integrations/github_actions.html

This checks for some common errors, makes single-quote vs double-quote consistent, does trailing commas (make diffs easier when adding items), etc

**Comment by lyricnz** [comment]
Or https://github.com/marketplace/actions/megalinter

**Comment by lyricnz** [comment]
I think mega-linter is the preferable option, since we can also use it to check html, markdown, etc (though I didn't enable any of that in PR).

**Comment by LukePrior** [comment]
Sounds good 👍

**Comment by lyricnz** [comment]
Feel free to review/merge. We’ll see if it raises pr

**Comment by LukePrior** [comment]
Alright we'll see how that goes.

**Comment by lyricnz** [comment]
Implemented mega-linter, but it's not clear exactly when it will raise PRs, and when it will commit directly.  Also, PRs from forks don't have the permissions to change code, so that doesn't work.

**Comment by lyricnz** [comment]
Looks like it added a commit to my PR (yay)
https://github.com/LukePrior/nbn-upgrade-map/pull/96
